"""add image_url to logged_meals

Revision ID: bc89d4b9708a
Revises: 318b665f888e
Create Date: 2026-04-27 20:46:28.966708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc89d4b9708a'
down_revision: Union[str, Sequence[str], None] = '318b665f888e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_meals', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logged_meals', 'image_url')
    # ### end Alembic commands ###
